apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-microservice
  labels:
    name: nodejs-microservice
spec:
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: <Service>
            port: 
              number: <Port>
